apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentstate.fullname" . }}-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
