version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sdk-ts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/sdk-py"
    schedule:
      interval: "weekly"
