repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -lc 'cargo fmt --all'
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: bash -lc 'cargo clippy --all-targets -- -D warnings'
        language: system
        pass_filenames: false
