/// Lean 4 proof certificate generator.
///
/// Converts an AgentState (Proof, Claim, DomainPack) triple into a Lean 4
/// source file that the Lean kernel can type-check. The certificate is
/// self-contained: it imports the domain's formal Lean module (if declared)
/// and produces a `theorem proof_certificate` whose type is the claim's
/// conclusion predicate.
///
/// ## Trust model
///
/// - **Premises** are modeled as `axiom` declarations. An axiom in Lean
///   represents a trusted external input — in this case, evidence that was
///   verified by an external process (e.g. a referenced publication, a WAL
///   state object at a pinned commit). The certificate documents *which*
///   external sources are assumed.
///
/// - **Domain inference rules** are declared in the domain's `formal.lean`
///   module as `theorem`s or `axiom`s. When the domain has a `lean_module`,
///   the certificate imports it and uses its theorems. When it does not, the
///   rules are emitted as local axioms — structurally sound, but not
///   machine-verified against domain logic.
///
/// - **The `proof_certificate` theorem** is a Lean proof term showing that
///   the conclusion follows from the premises via the rules. Lean's kernel
///   (the small trusted core) type-checks this term.
///
/// ## What this certifies
///
/// ✓ The proof DAG structure is correct (steps compose as declared)
/// ✓ Every declared premise is referenced in the derivation
/// ✓ Every inference step uses a rule declared in the domain
/// ✓ The conclusion follows from the premises by the domain's causal rules
///
/// ✗ NOT certified by Lean: the empirical truth of the premises
///   (those are verified by external processes and modeled as axioms)
use crate::{
    claim::{Claim, PremiseRef},
    domain::DomainPack,
    proof::{Proof, ProofStatus, StepKind},
};

/// Generate a Lean 4 proof certificate for the given proof+claim+domain.
pub fn generate_certificate(proof: &Proof, claim: &Claim, domain: &DomainPack) -> String {
    let mut out = String::new();

    // ── Header ────────────────────────────────────────────────────────────────
    out.push_str(&format!(
        "-- AgentState Proof Certificate\n\
         -- Generated by agentstate v{version}\n\
         --\n\
         -- Claim:    {claim_id}\n\
         -- Namespace: {ns}\n\
         -- Domain:   {domain}/{version_d}\n\
         -- Template: {template}\n\
         -- Proof ID: {proof_id}\n\
         -- Status:   {status}\n\
         -- Commit:   {commit}\n\
         --\n\
         -- To verify (requires Lean 4):\n\
         --   lake env lean {filename}\n\
         -- Or without Lake:\n\
         --   lean {filename}\n\
         --\n\
         -- What this file proves:\n\
         --   Given the axioms below (externally verified evidence), the conclusion\n\
         --   \"{predicate}\" follows by the domain's declared inference rules.\n\
         --   Lean's kernel verifies the proof term is well-typed.\n\n",
        version = env!("CARGO_PKG_VERSION"),
        claim_id = claim.id,
        ns = claim.ns,
        domain = domain.domain,
        version_d = domain.version,
        template = claim.template.as_deref().unwrap_or("(direct)"),
        proof_id = proof.proof_id,
        status = format!("{:?}", proof.status).to_lowercase(),
        commit = proof.commit,
        filename = format!("proof_{}.lean", &proof.proof_id[..8.min(proof.proof_id.len())]),
        predicate = claim.assertion.predicate,
    ));

    // ── Import domain module (Tier 2+) ────────────────────────────────────────
    let namespace = if let Some(module) = &domain.lean_module {
        out.push_str(&format!("import {}\n\n", module));
        out.push_str(&format!("open {}\n\n", module));
        Some(module.clone())
    } else {
        // No formal module — emit all rules as local axioms (Tier 1 fallback)
        out.push_str(
            "-- Note: this domain has no formal.lean companion.\n\
             -- Inference rules are emitted as local axioms (structurally sound,\n\
             -- not machine-verified against domain logic). To enable full Lean\n\
             -- verification, add lean_module to the domain pack and write formal.lean.\n\n",
        );
        None
    };

    // ── Namespace ─────────────────────────────────────────────────────────────
    let ns_ident = lean_ident(&proof.proof_id);
    out.push_str(&format!("namespace AgentState.Proof.«{}»\n\n", ns_ident));

    // ── Premise axioms ────────────────────────────────────────────────────────
    out.push_str("-- Ground assumptions\n");
    out.push_str("-- Each axiom represents externally verified evidence.\n");
    out.push_str(
        "-- The source IDs and roles are documented here for auditability.\n\n",
    );

    let mut premise_names: Vec<(String, String)> = Vec::new(); // (lean_name, role)
    for (i, premise) in claim.premises.iter().enumerate() {
        let role = premise.role();
        let assumption_id = premise.assumption_id();
        let lean_name = format!("premise_{}", i);
        let type_name = lean_role_type(role, &namespace);

        let comment = match premise {
            PremiseRef::Source { id, .. } => format!("source:{}", id),
            PremiseRef::WalState { ns, object_id, at_commit, .. } => {
                format!(
                    "wal:{}:{}{}",
                    ns,
                    object_id,
                    at_commit.as_deref().map(|c| format!("@{}", &c[..8.min(c.len())])).unwrap_or_default()
                )
            }
            PremiseRef::DomainAxiom { axiom_id, .. } => format!("axiom:{}", axiom_id),
            PremiseRef::PriorClaim { claim_id, .. } => format!("claim:{}", claim_id),
        };

        out.push_str(&format!(
            "axiom {} : {}  -- {} | role:{} | assumption:{}\n",
            lean_name, type_name, comment, role, assumption_id
        ));
        premise_names.push((lean_name, role.to_string()));
    }
    out.push('\n');

    // ── Local rule axioms (Tier 1 fallback — no domain module) ───────────────
    if namespace.is_none() {
        out.push_str("-- Domain inference rules (local axioms — see note above)\n");
        for step in &proof.steps {
            if matches!(step.kind, StepKind::Inference) {
                let rule_id = step.rule.split(':').last().unwrap_or(&step.rule);
                let conclusion_type = lean_pred_type(&step.conclusion_predicate);
                let premise_types: Vec<String> = step
                    .premises_used
                    .iter()
                    .filter_map(|&j| premise_names.get(j))
                    .map(|(_, role)| lean_role_type(role, &None))
                    .collect();
                let sig = if premise_types.is_empty() {
                    conclusion_type
                } else {
                    format!("{} → {}", premise_types.join(" → "), conclusion_type)
                };
                out.push_str(&format!(
                    "axiom {} : {}  -- rule: {}\n",
                    lean_ident(rule_id),
                    sig,
                    step.rule,
                ));
            }
        }
        out.push('\n');
    }

    // ── Proof certificate theorem ─────────────────────────────────────────────
    let conclusion_pred = lean_pred_type(&claim.assertion.predicate);

    if proof.status == ProofStatus::Refuted {
        out.push_str(&format!(
            "-- This claim was REFUTED: {}\n\
             -- No proof certificate is generated for refuted claims.\n\
             -- The Lean file is provided for structural documentation only.\n\n\
             -- theorem proof_certificate : {} := sorry  -- refuted\n",
            proof.refutation_reason.as_deref().unwrap_or("reason unspecified"),
            conclusion_pred,
        ));
    } else {
        // Build the proof term
        out.push_str(&format!(
            "-- Proof that \"{}\" follows from the premises\n-- via the domain's inference rules.\n",
            claim.assertion.predicate,
        ));

        // Function signature: (premise_0 : T0) → ... → conclusion
        let params: Vec<String> = premise_names
            .iter()
            .map(|(name, role)| format!("({} : {})", name, lean_role_type(role, &namespace)))
            .collect();

        out.push_str(&format!(
            "theorem proof_certificate\n    {} :\n    {} := by\n",
            params.join("\n    "),
            conclusion_pred,
        ));

        // Generate the proof body
        out.push_str(&build_proof_body(proof, &premise_names, domain, &namespace));
    }

    out.push_str(&format!("\nend AgentState.Proof.«{}»\n", ns_ident));
    out
}

/// Build the `by` tactic block for the proof certificate.
fn build_proof_body(
    proof: &Proof,
    premise_names: &[(String, String)],
    domain: &DomainPack,
    namespace: &Option<String>,
) -> String {
    let mut body = String::new();

    // Find the conclusion step — its premises_used tells us the full chain.
    let conclusion_step = proof.steps.iter().rev().find(|s| matches!(s.kind, StepKind::Conclusion));

    let template_id = proof
        .steps
        .iter()
        .rev()
        .find(|s| matches!(s.kind, StepKind::Conclusion))
        .and_then(|s| s.rule.split(':').last())
        .unwrap_or("direct");

    if namespace.is_some() {
        // Tier 2: use the domain module's theorem directly
        // The template theorem takes all premises as arguments.
        let args: Vec<String> = premise_names.iter().map(|(n, _)| n.clone()).collect();
        if args.is_empty() {
            body.push_str("  trivial\n");
        } else {
            body.push_str(&format!(
                "  exact {} {}\n",
                lean_ident(template_id),
                args.join(" ")
            ));
        }
    } else {
        // Tier 1: apply local rule axioms step by step
        // Build a let-binding chain through the inference steps.
        let mut step_exprs: Vec<String> = Vec::new();

        // Ground steps → premise variable names
        for step in &proof.steps {
            if matches!(step.kind, StepKind::Ground) {
                let expr = premise_names
                    .get(step.step_id)
                    .map(|(n, _)| n.clone())
                    .unwrap_or_else(|| "True.intro".to_string());
                step_exprs.push(expr);
            }
        }

        // Inference steps → apply rule axioms
        for step in &proof.steps {
            if matches!(step.kind, StepKind::Inference) {
                let rule_id = step.rule.split(':').last().unwrap_or("rule");
                let args: Vec<String> = step
                    .premises_used
                    .iter()
                    .filter_map(|&j| step_exprs.get(j).cloned())
                    .collect();
                let expr = if args.is_empty() {
                    lean_ident(rule_id)
                } else {
                    format!("({} {})", lean_ident(rule_id), args.join(" "))
                };
                step_exprs.push(expr);
            }
        }

        let final_expr = if let Some(conc) = conclusion_step {
            // The conclusion references all prior steps.
            if conc.premises_used.is_empty() {
                "trivial".to_string()
            } else if conc.premises_used.len() == 1 {
                step_exprs
                    .get(conc.premises_used[0])
                    .cloned()
                    .unwrap_or_else(|| "trivial".to_string())
            } else {
                let parts: Vec<String> = conc
                    .premises_used
                    .iter()
                    .filter_map(|&j| step_exprs.get(j).cloned())
                    .collect();
                format!("⟨{}⟩", parts.join(", "))
            }
        } else {
            "trivial".to_string()
        };

        body.push_str(&format!("  exact {}\n", final_expr));
    }

    body
}

// ── Naming helpers ─────────────────────────────────────────────────────────

/// Convert a role name like "allergy_history" to a Lean type name "AllergyHistory".
fn lean_role_type(role: &str, namespace: &Option<String>) -> String {
    let pascal = to_pascal_case(role);
    if namespace.is_some() {
        pascal // module already opened; use unqualified name
    } else {
        pascal
    }
}

/// Convert a predicate string to a Lean type name.
fn lean_pred_type(pred: &str) -> String {
    to_pascal_case(pred)
}

/// Convert snake_case / hyphen-case to a valid Lean identifier.
fn lean_ident(s: &str) -> String {
    // Replace characters invalid in Lean identifiers
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' || c == '.' { c } else { '_' })
        .collect()
}

/// Convert snake_case to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == ' ')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_converts_correctly() {
        assert_eq!(to_pascal_case("allergy_history"), "AllergyHistory");
        assert_eq!(to_pascal_case("safe_to_prescribe"), "SafeToPrescribe");
        assert_eq!(to_pascal_case("drug_interaction_db"), "DrugInteractionDb");
        assert_eq!(to_pascal_case("entity_solvent"), "EntitySolvent");
    }

    #[test]
    fn generate_certificate_produces_valid_lean_header() {
        use crate::{
            claim::{ClaimAssertion, ClaimRequest},
            domain::DomainRegistry,
            engine::build_proof,
        };

        let registry = DomainRegistry::new();
        let domain = registry.get("healthcare/v1").expect("healthcare domain");

        let req = ClaimRequest {
            domain: "healthcare/v1".to_string(),
            template: Some("drug_safety".to_string()),
            assertion: ClaimAssertion {
                predicate: "safe_to_prescribe".to_string(),
                subject: None,
                object: None,
                params: None,
            },
            premises: vec![
                crate::PremiseRef::Source { id: "pub-1".to_string(), role: "allergy_history".to_string() },
                crate::PremiseRef::Source { id: "pub-2".to_string(), role: "current_medications".to_string() },
                crate::PremiseRef::Source { id: "pub-3".to_string(), role: "dosage_evidence".to_string() },
            ],
            consequences: vec![],
            scope: None,
            cause: None,
            valid_until: None,
            required_signers: vec![],
        };

        let claim = req.into_claim("test".to_string());
        let proof = build_proof(&claim, domain, &[]);
        let cert = generate_certificate(&proof, &claim, domain);

        assert!(cert.contains("AgentState Proof Certificate"));
        assert!(cert.contains("namespace AgentState.Proof"));
        assert!(cert.contains("axiom premise_0"));
        assert!(cert.contains("axiom premise_1"));
        assert!(cert.contains("axiom premise_2"));
        assert!(cert.contains("theorem proof_certificate"));
    }
}
