name: release
on:
  push:
    tags: [ 'v*' ]
permissions:
  contents: write
  id-token: write
  packages: write
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/agentstate-server:${{ github.ref_name }}
      - name: SBOM (syft)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}/agentstate-server:${{ github.ref_name }}
      - name: Sign (cosign keyless)
        uses: sigstore/cosign-installer@v3
      - run: cosign sign --yes ghcr.io/${{ github.repository }}/agentstate-server:${{ github.ref_name }}
